### ISSUE TITLE
[Suggestion] Adding support for other distros via AppImage.

### ISSUE THREAD

**Issue by ZediAlreadyTaken** [ghostlexly/gpu-video-wallpaper#12]
~~I have created an AppImage which launches the GUI front-end.~~

~~This has the following benefits:~~

~~1. Adds support for non-Debian based distributions.~~
~~2. No need to install dependencies so `install.sh` is no longer needed.~~
~~3. User-friendliness.~~

~~You can download the AppImage here, I have attached all the files namely the .AppDir and the AppImage itself:~~
~~https://drive.google.com/drive/folders/1JPhaRby7Rjx3fO53JrH37a3wVKuT6O-8?usp=sharing (link is outdated, use my fork)~~

~~Edit: Python3-Pyqt5 dependency is not resolved. Please install it on your system, I'll try to fix this later (this is now fixed)~~

AppImage is not feasible for this project. Please close this thread.

**Comment by DARKBOW923** [comment]
I think you should open a pull request not an issue.

Also i will try this at gentoo GNU/Linux once i'm home, the install in gentoo (using the vanilla script) is sucessful but the uninstall is not possible.

**Comment by ZediAlreadyTaken** [comment]
~~I'm really sorry.. I'm very new to GitHub and Git so I don't really understand how to issue a pull request the way I was wishing to so I just filed an issue and attached a drive link to the files.~~

> install in gentoo (using the vanilla script) is sucessful but the uninstall is not possible.

~~I got rid of the install script all together because it is not needed for appimages.~~

**Comment by DARKBOW923** [comment]
> I'm really sorry.. I'm very new to GitHub and Git so I don't really understand how to issue a pull request the way I was wishing to so I just filed an issue and attached a drive link to the files.
> 
> > install in gentoo (using the vanilla script) is sucessful but the uninstall is not possible.
> 
> I got rid of the install script all together because it is not needed for appimages.

Its ok buddy don't worry :)

Anyways i suggest you to make a fork of the project and upload the appimage, so you'll have a fork of your program with separate issues sections, pull request, etc.

**Comment by ZediAlreadyTaken** [comment]
> Anyways i suggest you to make a fork of the project and upload the appimage, so you'll have a fork of your program with separate issues sections, pull request, etc.

~~Good idea, I will probably do that if the dev doesn't like the idea of an appimage.~~

~~Right now, I am struggling to figure out how to add python3-pyqt5 in the appimage.. can someone shine a light on this?~~

**Comment by DARKBOW923** [comment]
> > Anyways i suggest you to make a fork of the project and upload the appimage, so you'll have a fork of your program with separate issues sections, pull request, etc.
> 
> Good idea, I will probably do that if the dev doesn't like the idea of an appimage.
> 
> Right now, I am struggling to figure out how to add python3-pyqt5 in the appimage.. can someone shine a light on this?

I don't really know about this, but i think the appimage its like an installer? I think adding the note in the README.md that as a prerequisite to run the appimage you should install python3-pyqt5 would be a great idea.

**Comment by ZediAlreadyTaken** [comment]
> I don't really know about this, but i think the appimage its like an installer? I think adding the note in the README.md that as a prerequisite to run the appimage you should install python3-pyqt5 would be a great idea.

~~Appimage isn't an installer. AppImages are portable files which can run on any distribution since all the dependencies and other things are already inside the AppImage.~~

~~Adding a note in the README.md is a nice idea but honestly that defeats the whole purpose of the AppImage, I want the program to run without the user entering any terminal commands and for that I'd need to integrate the python module inside the appimage.~~

~~One Reddit user from a 4 year old thread seems to be suggesting to bundle python itself in the AppImage but that would increase the file size by a lot. I'll see what can be done.~~

**Comment by gjgress** [comment]
I don't think you're gonna be able to get around not bundling python into the AppImage, not without entirely reworking the GUI.

[Here](https://appimage-builder.readthedocs.io/en/latest/examples/pyqt.html)'s a reference that shows how to bundle PyQt5 in an AppImage.

**Comment by ZediAlreadyTaken** [comment]
~~Alright, dev can close this issue now. I have forked the project and added the AppImage myself. Thank you @gjgress I was finally able to integrate Python-PyQt5 with the help of a good friend of mine and your link helped tons!~~

**Comment by ghostlexly** [comment]
Thank you for your searches.
