### ISSUE TITLE
Vlc based version

### ISSUE THREAD

**Issue by exebook** [ghostlexly/gpu-video-wallpaper#15]
On my computer vlc plays 4k videos utilizing only 6% of one core, while mpv uses about 60%. My pc is built on Ryzen 5 3400G. Can this script run with vlc as the backend? 

I tried myself but I think vlc does not have a thing similar to `-wid` parameter.

**Comment by ghostlexly** [comment]
Thanks for your suggestion.
VLC does not include anything similar, i will investigate more deeply.
