### ISSUE TITLE
gpu-video-wallpaper: command not found

### ISSUE THREAD

**Issue by akshat-khosya** [ghostlexly/gpu-video-wallpaper#19]
![Screenshot from 2022-04-03 12-05-41](https://user-images.githubusercontent.com/76739180/161415110-2b1fe7f8-dfbc-40e4-823d-76150e28d592.png)
![Screenshot from 2022-04-03 12-05-41](https://user-images.githubusercontent.com/76739180/161415097-7bb28623-af23-4db5-809e-ecc18937a3dd.png)

**Comment by SwallowYourDreams** [comment]
From `readme.md`:

> CLI usage: **_video-wallpaper.sh_** [--start] [--stop] [--startup true|false] "video_path.mp4"

**Comment by Sahandi81** [comment]
same issue. same error with `video-wallpaper.sh` too !

**Comment by SwallowYourDreams** [comment]
> same issue. same error with `video-wallpaper.sh` too !

No issue if you use the parameters correctly. To start playback, you need to use the `--start` flag, as quoted above.

**Comment by 1ssb** [comment]
![Screenshot from 2023-05-26 12-20-13](https://github.com/ghostlexly/gpu-video-wallpaper/assets/40661648/bd73bd1e-8010-4dc6-8110-e6714a8d1809)

**Comment by 1ssb** [comment]
Nope not working, am I doing something wrong?

![Screenshot from 2023-05-26 12-37-43](https://github.com/ghostlexly/gpu-video-wallpaper/assets/40661648/41978738-0239-49c6-a366-6da5bb6877b3)
