### ISSUE TITLE
CPU usage high

### ISSUE THREAD

**Issue by pageza** [ghostlexly/gpu-video-wallpaper#2]
I like what this can achieve, however when I run this it is using 65-80% of each four cores on my cpu. I am running an i-5 6600k, 16GB RAM and GTX1070. I don't know if this is expected behaviour.

**Comment by NayamAmarshe** [comment]
I noticed multiple instances running in the background because I pressed 'Start' button too many times. To circumvent this, you can just kill xwinwrap manually and hit start again.
