### ISSUE TITLE
"No such process" & "No such file or directory" when trying to run

### ISSUE THREAD

**Issue by Lysime** [ghostlexly/gpu-video-wallpaper#20]
When I try to run the program using the terminal I get this result
![image_2022-05-16_000454703](https://user-images.githubusercontent.com/94706327/168495787-0de3921e-99c1-4cb0-9f66-85c2452a8335.png)
I don't have any clue what I'm doing wrong here, do you mind helping me?

**Comment by Lysime** [comment]
Btw I use Ubuntu Budgie 22.04 LTS

**Comment by SwallowYourDreams** [comment]
You're missing xwinwrap, most likely because ypu didn't follow the installation instructions and did not install video-wallpaper, just ran it. As part of the install process, xwinwrap is downloaded off of that project's website.

Please follow the instructions as written and report back.

**Comment by Lysime** [comment]
I actually did install it and made sure to follow as the readme.md said but it still has the same problem. And when I move the xwinwrap folder to the gpu-video-wallpaper folder, I get this error
![image](https://user-images.githubusercontent.com/94706327/168699214-64e67e74-5f28-4b53-baf6-e55ca5b996a1.png)

**Comment by SwallowYourDreams** [comment]
If you've run the installer, all files will be placed here: /home/$USER/.local/bin
Hence, you can just run video-wallpaper from any directory.

From what I'm looking at here, it looks like you're trying to run the script from /home/$USER/gpu-video-wallpaper (i.e. the files you've cloned off Github). Please remove the "./" from your first command. That should do the trick. Let me know how far this will get us.

Also note that video-wallpaper comes with a GUI (and creates a corresponding menu entry if you let it). That has the correct directory baked in.

**Comment by Lysime** [comment]
This is what I have when I remove the ./
![image](https://user-images.githubusercontent.com/94706327/168760298-263b470f-11da-4bd6-bc07-cf5558803da8.png)
Also even though I accepted to create a menu entry at the end of the installation, I don't find it in my applications menu

**Comment by Lysime** [comment]
The problem seems to have solved itself after a few tries. Thanks a lot for your help

**Comment by Sahandi81** [comment]
@Lysime
how do you solve it ? say that bro
