### ISSUE TITLE
mpv died, exit status 1

### ISSUE THREAD

**Issue by root2185** [ghostlexly/gpu-video-wallpaper#29]
```
Kernel: 6.3.6-artix1-1
arch: x86_64 
Desktop: bspwm v: 0.9.10
Distro: Artix Linux
```
```
video-wallpaper.sh --start ~/Videos/<video>
The wid option must be an integer: WID
Error parsing option wid (option parameter could not be parsed)
Setting commandline option --wid=WID failed.
Exiting... (Fatal error)
mpv died, exit status 1
```
I have one monitor.
If I understood correctly these are the commands that will be executed:

```
xrandr | grep " connected\|\*" | pcregrep -o1 '([0-9]{1,}[x]{1,1}[0-9+]{1,}) \('
3840x2160+0+0

xwinwrap -g 3840x2160+0+0 -fdt -ni -b -nf -un -o
xwinwrap: Error: couldn't create command line
...
```
I installed this app from the AUR:
`aur/ghostlexly-gpu-video-wallpaper 2021.11.26.r9.g8773e95-1 [installed]`

**Comment by ghostlexly** [comment]
Hey,

I have reverted the latest commit about WID, can you retry with the new changes ?

**Comment by root2185** [comment]
I cloned and installed the repo.
Same error as before.

**Comment by root2185** [comment]
That commit is the solution, see https://github.com/mpv-player/mpv/issues/7410#issuecomment-1241893652. 

You need to use `mpv -wid %WID`:
`"$scriptdir"/xwinwrap -g $item -fdt -ni -b -nf -un -o 1.0 -- mpv -wid %WID --loop --no-audio "$VIDEO_PATH" & disown`

Is the AUR package old maybe?
`aur/ghostlexly-gpu-video-wallpaper 2021.11.26.r9.g8773e95-1 [0+] [0.00%] [19 Sep 2022]`.
It should be a `-git` version since there are no releases.

**Comment by ghostlexly** [comment]
Merged back the commit.
Thanks for the infos, the package on AUR seems to be outdated.

**Comment by ItsZariep** [comment]
Sorry for the inconvenience, PKGBUILD updated, now it should work fine, also tested in Artix btw
