### ISSUE TITLE
 environmental variable $HOME for home dir

### ISSUE THREAD

**Issue by root2185** [ghostlexly/gpu-video-wallpaper#31]
The script uses:
`confdir="/home/$USER/.config/video-wallpaper"`
But sometimes it is not there, e.g. in my case it would be `/$USER/.config/video-wallpaper`.
Can you use $HOME instead?
`confdir="$HOME/.config/video-wallpaper"`

**Comment by ghostlexly** [comment]
I'll make a commit.
Thanks for the suggestion.
